# Use only for PyScaffold development. Execute `conda env create -f environment.yml`
name: pyscaffold
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - wheel
  - sphinx
  - flake8
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-virtualenv
  - pytest-fixture-config
  - pytest-shutil
  - pre_commit
  - twine
  - tox
  - virtualenv
  - pip
  - pip:
      - pyscaffold
      - sphinx_rtd_theme  # to build docs locally
      - -e .  # install git checkout of PyScaffold in editable mode
      - tqdm==4.36.1
      - mmh3==2.5.1
      - requests==2.22.0
      - syft==0.3.0
      - black>=20.8b1
      - pytest>=5.3.5
      - pytest-black>=0.3.8
      - jupyter>=1.0.0
      - papermill>=1.2.1